### ISSUE TITLE
Stitched video contains frozen frames

### ISSUE THREAD

**Issue by ArsalanDotMe** [ArsalanDotMe/VideoStitch#1]

**Comment by ArsalanDotMe** [comment]
fixed by re-encoding the cut clips rather than just simply copying the video in the specified duration.

**Comment by jasan-s** [comment]
can you elaborate your process @ArsalanDotMe  I was able to stick videos together but vlc crashes at the timestamp of when the first clip end and the 2nd begins(stitch point). I can use the mouse cursor to skip to the 2nd clip but last frames are frozen.

**Comment by ArsalanDotMe** [comment]
Do you have a specific test case? What version of ffmpeg are you using?

**Comment by MrPowerScripts** [comment]
Having the same issue. using `ffmpeg version 4.1.1`. with vlc the video crashes att he stitch between two concated videos. in quicktime the same videos plays the whole way through, but it freezes on the first video image (it's a single frame with audio), but plays the entire audo of both videosi. Very weird.
