### ISSUE TITLE
Re-publish to NPM to get updated safe handling

### ISSUE THREAD

**Issue by slyadams** [ArsalanDotMe/VideoStitch#4]
Hi,

I see you have made a change to call -safe 0, but this isn't in the published NPM package. Would it be possible publish 1.3.2 with this in?

Thanks!

**Comment by ArsalanDotMe** [comment]
Yeah sure I must have forgotten, just give me a couple of hours and I'll
update the npm repo.

**Comment by slyadams** [comment]
Thanks!

**Comment by ArsalanDotMe** [comment]
done. sorry for the delay, was caught up in some other urgent work. I've bumped the version to 1.4.0 now because this change alters the behavior of the library.
