### ISSUE TITLE
'Split' undefined.

### ISSUE THREAD

**Issue by NuroDev** [ArsalanDotMe/VideoStitch#5]
Unsure if the issue is to do with my [project](https://github.com/meadowcottage/kaplansays) or if the module itself. But in runtime, it returns the error `Cannot read property 'split' of undefined` 

Any ideas if it's my code or the module? 🤔

**Comment by ArsalanDotMe** [comment]
Check what you're passing to the module. I think you might be missing a parameter or sending a null or undefined.

**Comment by ArsalanDotMe** [comment]
You should send the full error stack you're getting so that I can give you more specific advice

**Comment by NuroDev** [comment]
I'll take a look into it now 😄 
Here's the full stack trace:
```
Uncaught TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (bundle.js:34744)
    at Object.171._process (bundle.js:34772)
    at s (bundle.js:1)
    at bundle.js:1
    at Object.174.file-extension (bundle.js:34856)
    at s (bundle.js:1)
    at bundle.js:1
    at Object.173../lib/videoconcat (bundle.js:34849)
    at s (bundle.js:1)
    at bundle.js:1
```

Code found in `bundle.js` on specified line is as follows:
```
var version = process.versions.node.split('.').map(function (value) {
  return parseInt(value, 10);
});
```

**Comment by ArsalanDotMe** [comment]
That's definitely very strange. What node version do you have? What prints
when you type `process.versions.node` into a node console?

**Comment by NuroDev** [comment]
Node Version: `7.0.0`
NPM version: `4.4.1`

Running `process.versions.node` in the console just returns: `'process.versions.node' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by ArsalanDotMe** [comment]
That looks like a bug. I would recommend sticking to LTS version of node.

**Comment by NuroDev** [comment]
Okay. Will maybe backdate to LTS version and see if it resolves it 😄

**Comment by NuroDev** [comment]
Sadly the issue is still there on the LTS version 😕 
Node Version: `6.10.1`

**Comment by ArsalanDotMe** [comment]
Sorry I was traveling yesterday so couldn't respond well from my phone. What you describe is either very strange bug or you're doing something wrong. Do what I do in this gif and let me know what you get:

![Getting node version](https://media.giphy.com/media/3oKIPd830COSxnCqB2/giphy.gif)

**Comment by NuroDev** [comment]
That is fine 😄 
And ah, my mistake. I ran that from cmd instead by mistake. 
This is the output when running from Powershell. Does seem to be an issue on my end 😕 
![](http://i.imgur.com/MSZ8mSR.png)

**Comment by ArsalanDotMe** [comment]
You first have to type `node`, press enter, and then type `process.versions.node`

**Comment by NuroDev** [comment]
Whoops! Messed that up again! 😆 
```
> process.versions.node
'6.10.1'
```

**Comment by ArsalanDotMe** [comment]
closed because could not reproduce the bug
